// Demo profile and portfolio copy lives here. Replace this file first when making the template your own.
export const PROFILE = {
  name: 'Mira Chen',
  shortName: 'MIRA',
  role: 'Designer, developer, and collector of unfinished ideas.',
  intro: 'I make digital things with a bit of warmth, a clear point of view, and no hurry to be clever.',
  location: 'Independent · Open to thoughtful collaborations',
  email: 'hello@yourdomain.com',
  socials: [
    { label: 'Portfolio notes', href: 'https://github.com/your-handle', mark: 'GH' },
    { label: 'Work updates', href: 'https://www.linkedin.com/in/your-handle', mark: 'in' },
  ],
};

export const PROJECTS = [
  {
    id: 'morrow',
    number: '01',
    name: 'Morrow',
    subtitle: 'A softer start to the day',
    category: 'Digital product · 2025',
    role: 'Product design, art direction, front-end',
    summary: 'A small morning ritual for people who want to buy less, choose well, and know where a thing came from.',
    detail: 'Morrow began with a question from a corner-shop owner: could online shopping feel more like being welcomed in than being hurried along? We rebuilt the storefront around short maker stories, clear materials, and a checkout that never tries to sell one more thing.',
    result: 'A calmer little shop, a shorter path to the useful stuff, and a much better place for the makers’ stories to live.',
    palette: ['#f2c16d', '#7d4935', '#254d4a'],
    motif: 'sunrise',
  },
  {
    id: 'weatherline',
    number: '02',
    name: 'Weatherline',
    subtitle: 'Forecasts with room to breathe',
    category: 'Web app · 2024',
    role: 'Concept, interface, creative development',
    summary: 'A neighbourhood weather board that gives the useful details first and lets the sky have the last word.',
    detail: 'The forecast is already full of numbers. Weatherline turns those numbers into a quiet daily picture: when the rain will start, which way the wind is leaning, and whether it is worth hanging the washing outside.',
    result: 'An at-a-glance forecast for the next few hours, with a hand-drawn weather scene that changes as the day does.',
    palette: ['#80b9bb', '#344e68', '#f2d99c'],
    motif: 'clouds',
  },
  {
    id: 'little-atlas',
    number: '03',
    name: 'Little Atlas',
    subtitle: 'A map made of local stories',
    category: 'Editorial · 2024',
    role: 'Identity, interaction, illustration',
    summary: 'A pocket-sized guide to the places that make a street feel like someone’s street.',
    detail: 'Little Atlas gathers the small landmarks you miss when you only follow the fastest route: the green bench that catches the last light, the baker who remembers your order, the book box that keeps refilling itself.',
    result: 'A living walking map with short audio notes, hand-drawn markers, and room for residents to add their own corners.',
    palette: ['#d78759', '#345847', '#e8d4a8'],
    motif: 'atlas',
  },
];

export const STOPS = [
  {
    id: 'gate',
    number: '00',
    title: 'The front gate',
    label: 'A little world, entered slowly',
    kicker: 'START HERE',
    note: 'There is no hurry. The house is a map: turn a corner, meet a project, stay if something catches your eye.',
    floor: 'yard',
  },
  {
    id: 'porch',
    number: '01',
    title: 'The porch',
    label: 'A few words before coming in',
    kicker: 'A NOTE FROM MIRA',
    note: 'I like the part of a project before it has a name. The scraps on the table, the wrong turns, the first version that makes somebody grin.',
    floor: 'lower',
  },
  {
    id: 'living',
    number: '02',
    title: 'The living room',
    label: 'Three things made with care',
    kicker: 'SELECTED WORK',
    note: 'These are a few recent collaborations. Click a lit frame to see what the brief was, what changed, and which decisions mattered.',
    floor: 'lower',
  },
  {
    id: 'table',
    number: '03',
    title: 'The kitchen table',
    label: 'Where rough ideas get useful',
    kicker: 'HOW I WORK',
    note: 'I start by listening for the thing people keep doing the hard way. Then I make a rough version, put it in front of someone, and stay curious about what breaks.',
    floor: 'lower',
  },
  {
    id: 'landing',
    number: '04',
    title: 'The upstairs landing',
    label: 'A few years, a few good turns',
    kicker: 'THE SHORT VERSION',
    note: 'I came up through small teams, patient mentors, and projects that needed both a sketchbook and a browser inspector. I still keep one of each close.',
    floor: 'upper',
  },
  {
    id: 'library',
    number: '05',
    title: 'The reading nook',
    label: 'Things I come back to',
    kicker: 'A SMALL PRACTICE',
    note: 'Good labels. A useful empty state. A little play in the right place. And the feeling that someone thought about the person on the other side of the screen.',
    floor: 'upper',
  },
  {
    id: 'studio',
    number: '06',
    title: 'The studio',
    label: 'Tools are only as good as the questions',
    kicker: 'AT THE DESK',
    note: 'Most days: Figma, a notebook, browser devtools, and enough tea to make the walk to the kettle feel like research. The stack changes; the care should not.',
    floor: 'upper',
  },
  {
    id: 'window',
    number: '07',
    title: 'The window seat',
    label: 'Room for whatever comes next',
    kicker: 'SAY HELLO',
    note: 'Have a good question, a knotty interface, or a project with a bit of heart in it? I would be glad to hear what you are thinking about.',
    floor: 'upper',
  },
];

export const ROUTE_NOTES = [
  { title: 'The first sketch', text: 'Start with a place, not a sitemap. The porch sets the pace; the house makes the sections feel like rooms rather than a stack of links.' },
  { title: 'A room for the work', text: 'Each picture frame opens a short case note. The story is kept close to the artefact: the reason it exists, the decisions behind it, and what changed.' },
  { title: 'A path you can learn', text: 'Scroll for the slow route, use A and D to hop between stops, or open the map when you already know where you want to go.' },
  { title: 'A window left open', text: 'The last stop is intentionally quiet. A good portfolio should make it easy to start a conversation, not bury the address under one more flourish.' },
];
